# generated by datamodel-codegen:
#   filename:  tutor-openapi.yaml
#   timestamp: 2026-06-09T05:33:03+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class Step(StrEnum):
    """
    One of the six coaching steps, in order.
    """

    clarify = 'clarify'
    examples = 'examples'
    approach = 'approach'
    plan = 'plan'
    implement = 'implement'
    test = 'test'


class Verdict(StrEnum):
    """
    The gate model's classification of the learner's answer.
    """

    pass_ = 'pass'
    retry = 'retry'
    off_topic = 'off_topic'
    question = 'question'


class Role(StrEnum):
    user = 'user'
    coach = 'coach'


class SessionOrigin(StrEnum):
    your_turn = 'your_turn'
    problem_page = 'problem_page'


class SessionStatus(StrEnum):
    active = 'active'
    completed = 'completed'


class HealthStatus(BaseModel):
    status: str = Field(..., examples=['ok'])


class ApiError(BaseModel):
    error: str
    detail: str | None = None
    hint: str | None = None


class CoachMessage(BaseModel):
    role: Role
    step: Step
    content: str
    createdAtEpochMs: int


class StepScore(BaseModel):
    step: Step
    score: int


class GateVerdict(BaseModel):
    """
    The structured gate result. On the server path it is produced by the gate model (strict
    tool-use); on the BYOK path the browser computes it and posts it here. The server re-derives
    advancement as `verdict == pass` — never trusting a model-supplied advance flag.

    """

    verdict: Verdict
    score: int | None = Field(
        0, description='Confidence the gate is cleared; one of {0,10,…,100}.'
    )
    rubricHits: list[str] | None = None
    missing: list[str] | None = None
    hint: str | None = ''
    nextHintLevel: int | None = 0


class CoachSession(BaseModel):
    sessionId: UUID
    problemId: str
    origin: SessionOrigin
    status: SessionStatus
    currentStep: Step
    stepIndex: int
    completed: bool
    messages: list[CoachMessage]
    scores: list[StepScore]
    rubricVersion: str


class SessionCreateRequest(BaseModel):
    problemId: str = Field(
        ..., examples=['data-structures-and-algorithms/arrays/two-sum']
    )
    origin: SessionOrigin | None = 'your_turn'


class TurnRequest(BaseModel):
    step: Step
    turnId: UUID | None = Field(
        None,
        description='Client-generated idempotency key; re-POST replays the committed result.',
    )
    text: str = Field(..., description="The learner's answer / message for this step.")
    code: str | None = None
    language: str | None = None
    runResult: str | None = Field(
        None,
        description='stdout / status from /api/run (cortex go-judge), used by implement/test.',
    )


class ByokRecordRequest(BaseModel):
    step: Step
    turnId: UUID | None = None
    text: str
    coachReply: str = Field(
        ..., description="The reply the browser got from the user's provider."
    )
    verdict: GateVerdict
    code: str | None = None
    language: str | None = None
    runResult: str | None = None


class PromptBundle(BaseModel):
    step: Step
    system: str = Field(
        ...,
        description='The assembled system prompt (solution withheld pre-implement).',
    )
    messages: list[CoachMessage]
    model: str = Field(
        ..., description='The model id the browser should request from the provider.'
    )


class TurnUsage(BaseModel):
    inputTokens: int | None = None
    outputTokens: int | None = None
    cacheReadTokens: int | None = None
    cacheWriteTokens: int | None = None
    costUsd: float | None = None


class TurnResult(BaseModel):
    """
    The committed outcome of a turn (also the `done` SSE event payload).
    """

    sessionId: UUID
    step: Step = Field(..., description='The step that was evaluated.')
    stepIndex: int = Field(..., description='Current step index AFTER the turn.')
    verdict: Verdict
    score: int | None = None
    advanced: bool
    completed: bool
    hint: str | None = None
    reply: CoachMessage
    usage: TurnUsage | None = None


class Type(StrEnum):
    state = 'state'


class TurnStateEvent(BaseModel):
    type: Literal['state']
    session: CoachSession


class Type1(StrEnum):
    token = 'token'


class TurnTokenEvent(BaseModel):
    type: Literal['token']
    text: str


class Type2(StrEnum):
    done = 'done'


class TurnDoneEvent(BaseModel):
    type: Literal['done']
    result: TurnResult


class Type3(StrEnum):
    error = 'error'


class TurnErrorEvent(BaseModel):
    type: Literal['error']
    error: ApiError


class TurnEvent(
    RootModel[TurnStateEvent | TurnTokenEvent | TurnDoneEvent | TurnErrorEvent]
):
    root: TurnStateEvent | TurnTokenEvent | TurnDoneEvent | TurnErrorEvent = Field(
        ..., discriminator='type'
    )
