# generated by datamodel-codegen:
#   filename:  tutor-openapi.yaml
#   timestamp: 2026-06-19T15:53:02+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class Step(StrEnum):
    """
    A coaching step. The `problem` track runs the six coding steps
    (clarify → examples → approach → plan → implement → test); the `conceptual` track runs the
    four understanding steps (explain → apply → analyze → defend).

    """

    clarify = 'clarify'
    examples = 'examples'
    approach = 'approach'
    plan = 'plan'
    implement = 'implement'
    test = 'test'
    explain = 'explain'
    apply = 'apply'
    analyze = 'analyze'
    defend = 'defend'


class Verdict(StrEnum):
    """
    The gate model's classification of the learner's answer.
    """

    pass_ = 'pass'
    retry = 'retry'
    off_topic = 'off_topic'
    question = 'question'


class Role(StrEnum):
    user = 'user'
    coach = 'coach'


class SessionOrigin(StrEnum):
    your_turn = 'your_turn'
    problem_page = 'problem_page'


class SessionStatus(StrEnum):
    active = 'active'
    completed = 'completed'


class Track(StrEnum):
    """
    Which coaching ladder a session runs — `problem` (the six-step coding interview) or
    `conceptual` (the four-step understanding check for prose lessons). Pinned at creation.

    """

    problem = 'problem'
    conceptual = 'conceptual'


class HealthStatus(BaseModel):
    status: str = Field(..., examples=['ok'])


class ApiError(BaseModel):
    error: str
    detail: str | None = None
    hint: str | None = None


class Tier(StrEnum):
    """
    The caller's coach tier — `homelab` (server key) or `byok` (client-direct).
    """

    homelab = 'homelab'
    byok = 'byok'


class ModelOption(BaseModel):
    key: str = Field(
        ..., description='Stable catalog key to send as SessionCreateRequest.model.'
    )
    display: str = Field(..., description='Human-readable label for the model picker.')
    provider: str = Field(..., description='Backend family (e.g. anthropic).')


class Whoami(BaseModel):
    sub: str
    preferredUsername: str
    tier: Tier
    defaultModel: str = Field(
        ..., description='Catalog key used when SessionCreateRequest.model is omitted.'
    )
    availableModels: list[ModelOption]


class CoachMessage(BaseModel):
    role: Role
    step: Step
    content: str
    createdAtEpochMs: int


class StepScore(BaseModel):
    step: Step
    score: int


class GateVerdict(BaseModel):
    """
    The structured gate result. On the server path it is produced by the gate model (strict
    tool-use); on the BYOK path the browser computes it and posts it here. The server re-derives
    advancement as `verdict == pass` — never trusting a model-supplied advance flag.

    """

    verdict: Verdict
    score: int | None = Field(
        0, description='Confidence the gate is cleared; one of {0,10,…,100}.'
    )
    rubricHits: list[str] | None = None
    missing: list[str] | None = None
    hint: str | None = ''
    nextHintLevel: int | None = 0


class CoachSession(BaseModel):
    sessionId: UUID
    problemId: str
    origin: SessionOrigin
    track: Track | None = Field(
        None,
        description='Which coaching ladder this session runs (pinned at creation; defaults to problem).',
    )
    status: SessionStatus
    currentStep: Step
    stepIndex: int
    completed: bool
    messages: list[CoachMessage]
    scores: list[StepScore]
    rubricVersion: str
    byok: bool | None = Field(
        None,
        description='Tier, pinned at creation (server-authoritative): false = homelab (server-side gate +\ncoach via `submitTurn`), true = BYOK (client-direct via `getPromptBundle` +\n`recordByokTurn`; `submitTurn` answers 403). `reset` re-derives the tier.\n',
    )
    model: str | None = Field(
        None,
        description="The session's chosen coach model, by stable catalog key (null on pre-selection sessions\n→ the tier default applies). Echoes `SessionCreateRequest.model`.\n",
    )


class SessionCreateRequest(BaseModel):
    problemId: str = Field(
        ...,
        description="The cortex chapter's join key: `<book>/<hierarchical-chapter-slug>`, identical to the\nchapter's frontend URL path. The slug mirrors the directory tree (ordering prefixes\nstripped), so it's stable across chapter reordering.\n",
        examples=[
            'data-structures-and-algorithms/linear-structures/arrays/pattern-two-pointers-reduction/problems/two-sum'
        ],
    )
    origin: SessionOrigin | None = 'your_turn'
    track: Track | None = Field(
        'problem',
        description='Which coaching ladder to run — `conceptual` for a prose-lesson understanding check\n(the `concept-coach` block), else `problem`. Pinned at creation; `reset` carries it forward.\n',
    )
    model: str | None = Field(
        None,
        description="Optional coach model, by stable catalog **key** (e.g. `claude-sonnet`, `claude-haiku`;\nsee `GET /v1/whoami` → `availableModels`). Omit for the tier default. Validated\nserver-side against the caller's tier allow-list (422 if unknown/disallowed) and pinned\nat creation — a `model` on a resume is ignored; `reset` to change it.\n",
    )


class TurnRequest(BaseModel):
    step: Step
    turnId: UUID | None = Field(
        None,
        description='Client-generated idempotency key; re-POST replays the committed result.',
    )
    text: str = Field(..., description="The learner's answer / message for this step.")
    code: str | None = None
    language: str | None = None
    runResult: str | None = Field(
        None,
        description='stdout / status from /api/run (cortex go-judge), used by implement/test.',
    )


class ByokRecordRequest(BaseModel):
    step: Step
    turnId: UUID | None = None
    text: str
    coachReply: str = Field(
        ..., description="The reply the browser got from the user's provider."
    )
    verdict: GateVerdict
    code: str | None = None
    language: str | None = None
    runResult: str | None = None


class PromptBundle(BaseModel):
    step: Step
    system: str = Field(
        ...,
        description='The assembled system prompt (solution withheld pre-implement).',
    )
    messages: list[CoachMessage]
    model: str = Field(
        ..., description='The model id the browser should request from the provider.'
    )


class TurnUsage(BaseModel):
    inputTokens: int | None = None
    outputTokens: int | None = None
    cacheReadTokens: int | None = None
    cacheWriteTokens: int | None = None
    costUsd: float | None = None


class TurnResult(BaseModel):
    """
    The committed outcome of a turn (also the `done` SSE event payload).
    """

    sessionId: UUID
    step: Step = Field(..., description='The step that was evaluated.')
    stepIndex: int = Field(..., description='Current step index AFTER the turn.')
    verdict: Verdict
    score: int | None = None
    advanced: bool
    completed: bool
    hint: str | None = None
    reply: CoachMessage
    usage: TurnUsage | None = None


class Type(StrEnum):
    state = 'state'


class TurnStateEvent(BaseModel):
    type: Literal['state']
    session: CoachSession


class Type1(StrEnum):
    token = 'token'


class TurnTokenEvent(BaseModel):
    type: Literal['token']
    text: str


class Type2(StrEnum):
    done = 'done'


class TurnDoneEvent(BaseModel):
    type: Literal['done']
    result: TurnResult


class Type3(StrEnum):
    error = 'error'


class TurnErrorEvent(BaseModel):
    type: Literal['error']
    error: ApiError


class TurnEvent(
    RootModel[TurnStateEvent | TurnTokenEvent | TurnDoneEvent | TurnErrorEvent]
):
    root: TurnStateEvent | TurnTokenEvent | TurnDoneEvent | TurnErrorEvent = Field(
        ..., discriminator='type'
    )
